const dataSources = [
  {
    id: "revenue-aggregate",
    name: "Revenue Aggregate",
    kind: "aggregate",
    status: "live",
    description: "Normalized revenue view across connected payment providers.",
    endpoint: "internal://revenue",
    auth: "none",
    refreshIntervalMs: 60000,
    lastSyncAt: "",
    owner: "Revenue",
    fields: [
      { key: "timestamp", label: "Timestamp", type: "time" },
      { key: "series", label: "Series", type: "string" },
      { key: "provider", label: "Provider", type: "string" },
      { key: "received_at", label: "Received At", type: "time" },
      { key: "channel", label: "Channel", type: "string" },
      { key: "amount", label: "Amount", type: "number" },
      { key: "currency", label: "Currency", type: "string" },
      { key: "value", label: "Value", type: "number" },
      { key: "normalized_value", label: "Normalized Value", type: "number" },
      { key: "note", label: "Note", type: "string" },
    ],
  },
  {
    id: "zhupay-payments",
    name: "Zhupay Payments",
    kind: "zhupay",
    status: "polling",
    description: "Real Zhupay merchant balance, paid orders, and payment notifications.",
    endpoint: "https://pay.lxsd.cn",
    auth: "rsa",
    refreshIntervalMs: 60000,
    lastSyncAt: "",
    owner: "Revenue",
    fields: [
      { key: "captured_at", label: "Captured At", type: "time" },
      { key: "balance", label: "Merchant Balance", type: "number" },
      { key: "order_money_today", label: "Today Revenue", type: "number" },
      { key: "order_money_lastday", label: "Yesterday Revenue", type: "number" },
      { key: "order_num", label: "Total Orders", type: "number" },
      { key: "order_num_today", label: "Today Orders", type: "number" },
      { key: "trade_no", label: "Zhupay Trade No", type: "string" },
      { key: "out_trade_no", label: "Merchant Order No", type: "string" },
      { key: "type", label: "Payment Type", type: "string" },
      { key: "status", label: "Payment Status", type: "number" },
      { key: "name", label: "Product", type: "string" },
      { key: "money", label: "Order Amount", type: "number" },
      { key: "addtime", label: "Created At", type: "time" },
      { key: "endtime", label: "Paid At", type: "time" },
    ],
  },
  {
    id: "manual-revenue",
    name: "Manual Revenue",
    kind: "manual",
    status: "live",
    description: "Manually entered revenue for offline transfers, crypto payments, and non-standard channels.",
    endpoint: "internal://manual-revenue",
    auth: "none",
    refreshIntervalMs: 60000,
    lastSyncAt: "",
    owner: "Revenue",
    fields: [
      { key: "id", label: "Entry ID", type: "string" },
      { key: "channel", label: "Channel", type: "string" },
      { key: "amount", label: "Amount", type: "number" },
      { key: "currency", label: "Currency", type: "string" },
      { key: "note", label: "Note", type: "string" },
      { key: "received_at", label: "Received At", type: "time" },
      { key: "created_at", label: "Created At", type: "time" },
    ],
  },
  {
    id: "creem-payments",
    name: "Creem Payments",
    kind: "creem",
    status: "polling",
    description: "Real Creem transactions, customers, subscriptions, and webhook events.",
    endpoint: "https://api.creem.io",
    auth: "api-key",
    refreshIntervalMs: 3600000,
    lastSyncAt: "",
    owner: "Revenue",
    fields: [
      { key: "captured_at", label: "Captured At", type: "time" },
      { key: "total_revenue", label: "Total Revenue", type: "number" },
      { key: "today_revenue", label: "Today Revenue", type: "number" },
      { key: "transaction_count", label: "Transactions", type: "number" },
      { key: "customer_count", label: "Customers", type: "number" },
      { key: "active_subscription_count", label: "Active Subscriptions", type: "number" },
      { key: "id", label: "Transaction ID", type: "string" },
      { key: "type", label: "Transaction Type", type: "string" },
      { key: "status", label: "Transaction Status", type: "string" },
      { key: "amount_paid", label: "Amount Paid", type: "number" },
      { key: "refunded_amount", label: "Refunded Amount", type: "number" },
      { key: "currency", label: "Currency", type: "string" },
      { key: "customer_id", label: "Customer ID", type: "string" },
      { key: "subscription_id", label: "Subscription ID", type: "string" },
      { key: "source_created_at", label: "Created At", type: "time" },
    ],
  },
  {
    id: "sub2api-usage",
    name: "Sub2API Usage",
    kind: "sub2api",
    status: "polling",
    description: "Sub2API usage spend converted into earned revenue at the configured profit rate.",
    endpoint: "https://s2a.ohmycdn.com",
    auth: "api-key",
    refreshIntervalMs: 60000,
    lastSyncAt: "",
    owner: "Revenue",
    fields: [
      { key: "timestamp", label: "Timestamp", type: "time" },
      { key: "series", label: "Series", type: "string" },
      { key: "channel", label: "Channel", type: "string" },
      { key: "group_id", label: "Group ID", type: "number" },
      { key: "total_spend", label: "Total Spend", type: "number" },
      { key: "earned_revenue", label: "Earned Revenue", type: "number" },
      { key: "today_spend", label: "Today Spend", type: "number" },
      { key: "today_earned", label: "Today Earned", type: "number" },
      { key: "requests", label: "Requests", type: "number" },
      { key: "profit_rate", label: "Profit Rate", type: "number" },
      { key: "value", label: "Value", type: "number" },
    ],
  },
];

const metrics = [
  {
    id: "metric-aggregate-today-revenue",
    key: "aggregate_today_revenue",
    name: "Today Revenue",
    description: "Normalized paid revenue across payment providers for the current day.",
    dataSourceId: "revenue-aggregate",
    field: "value",
    timeField: "timestamp",
    aggregation: "latest",
    format: "currency",
    unit: "USD",
    dimensions: ["provider"],
  },
  {
    id: "metric-aggregate-total-revenue",
    key: "aggregate_total_revenue",
    name: "Total Revenue",
    description: "Normalized paid revenue across all connected payment providers.",
    dataSourceId: "revenue-aggregate",
    field: "value",
    timeField: "timestamp",
    aggregation: "latest",
    format: "currency",
    unit: "USD",
    dimensions: ["provider"],
  },
  {
    id: "metric-aggregate-transaction-count",
    key: "aggregate_transaction_count",
    name: "Transactions",
    description: "Paid transaction count across connected payment providers.",
    dataSourceId: "revenue-aggregate",
    field: "value",
    timeField: "timestamp",
    aggregation: "latest",
    format: "number",
    dimensions: ["provider"],
  },
  {
    id: "metric-aggregate-customer-count",
    key: "aggregate_customer_count",
    name: "Customers",
    description: "Known customer count across providers that expose customer records.",
    dataSourceId: "revenue-aggregate",
    field: "value",
    timeField: "timestamp",
    aggregation: "latest",
    format: "number",
    dimensions: ["provider"],
  },
  {
    id: "metric-aggregate-revenue-trend",
    key: "aggregate_revenue_trend",
    name: "Daily Revenue",
    description: "Daily provider revenue and normalized daily total revenue in one chart.",
    dataSourceId: "revenue-aggregate",
    field: "value",
    timeField: "timestamp",
    aggregation: "sum",
    format: "currency",
    unit: "USD",
    dimensions: ["series"],
  },
  {
    id: "metric-aggregate-revenue-entries",
    key: "aggregate_revenue_entries",
    name: "Revenue Entries",
    description: "Latest revenue entries from Zhupay, Creem, manual income, and Sub2API earnings channels.",
    dataSourceId: "revenue-aggregate",
    field: "normalized_value",
    timeField: "received_at",
    aggregation: "latest",
    format: "currency",
    unit: "USD",
    dimensions: ["provider", "channel", "currency"],
  },
  {
    id: "metric-manual-today-revenue",
    key: "manual_today_revenue",
    name: "Manual Today Revenue",
    description: "Manual revenue entries received today in the configured reporting currency.",
    dataSourceId: "manual-revenue",
    field: "amount",
    timeField: "received_at",
    aggregation: "latest",
    format: "currency",
    unit: "USD",
    dimensions: ["channel", "currency"],
  },
  {
    id: "metric-manual-total-revenue",
    key: "manual_total_revenue",
    name: "Manual Total Revenue",
    description: "All manual revenue entries normalized to the configured reporting currency.",
    dataSourceId: "manual-revenue",
    field: "amount",
    timeField: "received_at",
    aggregation: "latest",
    format: "currency",
    unit: "USD",
    dimensions: ["channel", "currency"],
  },
  {
    id: "metric-manual-entry-count",
    key: "manual_entry_count",
    name: "Manual Entries",
    description: "Count of manually entered revenue records.",
    dataSourceId: "manual-revenue",
    field: "id",
    timeField: "received_at",
    aggregation: "count",
    format: "number",
    dimensions: ["channel", "currency"],
  },
  {
    id: "metric-manual-revenue-trend",
    key: "manual_revenue_trend",
    name: "Manual Revenue Trend",
    description: "Manual revenue entries grouped by channel and normalized to reporting currency.",
    dataSourceId: "manual-revenue",
    field: "amount",
    timeField: "received_at",
    aggregation: "sum",
    format: "currency",
    unit: "USD",
    dimensions: ["channel", "currency"],
  },
  {
    id: "metric-manual-recent-entries",
    key: "manual_recent_entries",
    name: "Manual Recent Entries",
    description: "Latest manually entered revenue records.",
    dataSourceId: "manual-revenue",
    field: "amount",
    timeField: "received_at",
    aggregation: "latest",
    format: "currency",
    unit: "USD",
    dimensions: ["channel", "currency"],
  },
  {
    id: "metric-zhupay-today-revenue",
    key: "zhupay_today_revenue",
    name: "Today Revenue",
    description: "Paid Zhupay order revenue reported by merchant info.",
    dataSourceId: "zhupay-payments",
    field: "order_money_today",
    timeField: "captured_at",
    aggregation: "latest",
    format: "currency",
    unit: "CNY",
    dimensions: [],
  },
  {
    id: "metric-zhupay-balance",
    key: "zhupay_balance",
    name: "Merchant Balance",
    description: "Current Zhupay merchant balance.",
    dataSourceId: "zhupay-payments",
    field: "balance",
    timeField: "captured_at",
    aggregation: "latest",
    format: "currency",
    unit: "CNY",
    dimensions: [],
  },
  {
    id: "metric-zhupay-today-orders",
    key: "zhupay_today_orders",
    name: "Today Orders",
    description: "Number of paid orders today.",
    dataSourceId: "zhupay-payments",
    field: "order_num_today",
    timeField: "captured_at",
    aggregation: "latest",
    format: "number",
    dimensions: [],
  },
  {
    id: "metric-zhupay-total-orders",
    key: "zhupay_total_orders",
    name: "Total Orders",
    description: "Total Zhupay order count reported by merchant info.",
    dataSourceId: "zhupay-payments",
    field: "order_num",
    timeField: "captured_at",
    aggregation: "latest",
    format: "number",
    dimensions: [],
  },
  {
    id: "metric-zhupay-revenue-trend",
    key: "zhupay_revenue_trend",
    name: "Revenue Trend",
    description: "Paid Zhupay order amount aggregated by time bucket.",
    dataSourceId: "zhupay-payments",
    field: "money",
    timeField: "endtime",
    aggregation: "sum",
    format: "currency",
    unit: "CNY",
    dimensions: ["type"],
  },
  {
    id: "metric-zhupay-recent-orders",
    key: "zhupay_recent_orders",
    name: "Recent Paid Orders",
    description: "Latest paid orders synced from Zhupay.",
    dataSourceId: "zhupay-payments",
    field: "money",
    timeField: "endtime",
    aggregation: "latest",
    format: "currency",
    unit: "CNY",
    dimensions: ["type", "status"],
  },
  {
    id: "metric-creem-today-revenue",
    key: "creem_today_revenue",
    name: "Creem Today Revenue",
    description: "Net paid Creem revenue for the current day in the configured reporting currency.",
    dataSourceId: "creem-payments",
    field: "today_revenue",
    timeField: "captured_at",
    aggregation: "latest",
    format: "currency",
    unit: "USD",
    dimensions: [],
  },
  {
    id: "metric-creem-total-revenue",
    key: "creem_total_revenue",
    name: "Creem Total Revenue",
    description: "Net paid Creem revenue synced into DataOcean.",
    dataSourceId: "creem-payments",
    field: "total_revenue",
    timeField: "captured_at",
    aggregation: "latest",
    format: "currency",
    unit: "USD",
    dimensions: [],
  },
  {
    id: "metric-creem-customer-count",
    key: "creem_customer_count",
    name: "Creem Customers",
    description: "Customers synced from Creem.",
    dataSourceId: "creem-payments",
    field: "customer_count",
    timeField: "captured_at",
    aggregation: "latest",
    format: "number",
    dimensions: [],
  },
  {
    id: "metric-creem-active-subscriptions",
    key: "creem_active_subscriptions",
    name: "Creem Active Subscriptions",
    description: "Active and trialing subscriptions synced from Creem.",
    dataSourceId: "creem-payments",
    field: "active_subscription_count",
    timeField: "captured_at",
    aggregation: "latest",
    format: "number",
    dimensions: [],
  },
  {
    id: "metric-creem-revenue-trend",
    key: "creem_revenue_trend",
    name: "Creem Revenue Trend",
    description: "Net Creem transaction revenue aggregated by time bucket.",
    dataSourceId: "creem-payments",
    field: "amount_paid",
    timeField: "source_created_at",
    aggregation: "sum",
    format: "currency",
    unit: "USD",
    dimensions: ["type", "status"],
  },
  {
    id: "metric-creem-recent-transactions",
    key: "creem_recent_transactions",
    name: "Creem Recent Transactions",
    description: "Latest transactions synced from Creem.",
    dataSourceId: "creem-payments",
    field: "amount_paid",
    timeField: "source_created_at",
    aggregation: "latest",
    format: "currency",
    unit: "USD",
    dimensions: ["type", "status", "currency"],
  },
  {
    id: "metric-sub2api-today-profit",
    key: "sub2api_today_profit",
    name: "Sub2API Today Earned",
    description: "Today earned revenue from configured Sub2API channels at the configured profit rate.",
    dataSourceId: "sub2api-usage",
    field: "today_earned",
    timeField: "timestamp",
    aggregation: "latest",
    format: "currency",
    unit: "USD",
    dimensions: ["channel"],
  },
  {
    id: "metric-sub2api-total-profit",
    key: "sub2api_total_profit",
    name: "Sub2API Total Earned",
    description: "Cumulative earned revenue from configured Sub2API channels at the configured profit rate.",
    dataSourceId: "sub2api-usage",
    field: "earned_revenue",
    timeField: "timestamp",
    aggregation: "latest",
    format: "currency",
    unit: "USD",
    dimensions: ["channel"],
  },
  {
    id: "metric-sub2api-total-spend",
    key: "sub2api_total_spend",
    name: "Sub2API Total Spend",
    description: "Cumulative actual cost reported by the configured Sub2API groups.",
    dataSourceId: "sub2api-usage",
    field: "total_spend",
    timeField: "timestamp",
    aggregation: "latest",
    format: "currency",
    unit: "USD",
    dimensions: ["channel"],
  },
  {
    id: "metric-sub2api-request-count",
    key: "sub2api_request_count",
    name: "Sub2API Requests",
    description: "Total request count across configured Sub2API groups.",
    dataSourceId: "sub2api-usage",
    field: "requests",
    timeField: "timestamp",
    aggregation: "latest",
    format: "number",
    dimensions: ["channel"],
  },
  {
    id: "metric-sub2api-profit-trend",
    key: "sub2api_profit_trend",
    name: "Sub2API Daily Earned",
    description: "Daily earned revenue by Sub2API channel plus total.",
    dataSourceId: "sub2api-usage",
    field: "value",
    timeField: "timestamp",
    aggregation: "sum",
    format: "currency",
    unit: "USD",
    dimensions: ["series"],
  },
  {
    id: "metric-sub2api-channel-breakdown",
    key: "sub2api_channel_breakdown",
    name: "Sub2API Channel Breakdown",
    description: "Cost, earned revenue, requests, and profit rate for configured Sub2API channels.",
    dataSourceId: "sub2api-usage",
    field: "earned_revenue",
    timeField: "timestamp",
    aggregation: "latest",
    format: "currency",
    unit: "USD",
    dimensions: ["channel"],
  },
];

const aggregatePanels = [
  {
    id: "panel-aggregate-today-revenue",
    title: "Today Revenue",
    renderer: "kpi",
    query: { dataSourceId: "revenue-aggregate", metric: "aggregate_today_revenue", timeRange: "1d", refreshIntervalMs: 60000 },
    encoding: { value: "value" },
    style: { colorIntent: "positive" },
    layout: { x: 0, y: 0, w: 3, h: 1 },
    description: "Normalized revenue collected today.",
  },
  {
    id: "panel-aggregate-total-revenue",
    title: "Total Revenue",
    renderer: "kpi",
    query: { dataSourceId: "revenue-aggregate", metric: "aggregate_total_revenue", timeRange: "all", refreshIntervalMs: 60000 },
    encoding: { value: "value" },
    style: { colorIntent: "positive" },
    layout: { x: 3, y: 0, w: 3, h: 1 },
    description: "Normalized lifetime paid revenue.",
  },
  {
    id: "panel-aggregate-transactions",
    title: "Transactions",
    renderer: "kpi",
    query: { dataSourceId: "revenue-aggregate", metric: "aggregate_transaction_count", timeRange: "all", refreshIntervalMs: 60000 },
    encoding: { value: "value" },
    style: { colorIntent: "neutral" },
    layout: { x: 6, y: 0, w: 3, h: 1 },
    description: "Paid transactions from connected providers.",
  },
  {
    id: "panel-aggregate-customers",
    title: "Customers",
    renderer: "kpi",
    query: { dataSourceId: "revenue-aggregate", metric: "aggregate_customer_count", timeRange: "all", refreshIntervalMs: 60000 },
    encoding: { value: "value" },
    style: { colorIntent: "neutral" },
    layout: { x: 9, y: 0, w: 3, h: 1 },
    description: "Known customers from customer-aware providers.",
  },
  {
    id: "panel-aggregate-revenue-trend",
    title: "Daily Revenue by Provider",
    renderer: "lightweight-timeseries",
    query: { dataSourceId: "revenue-aggregate", metric: "aggregate_revenue_trend", timeRange: "1m", refreshIntervalMs: 60000 },
    encoding: { x: "timestamp", y: "value", color: "series" },
    style: { seriesStyle: "line", colorIntent: "primary" },
    interactions: { crosshair: true, zoom: true, rangeSwitcher: true },
    layout: { x: 0, y: 1, w: 12, h: 4 },
    description: "Daily Zhupay, Creem, Manual, Sub2API, and normalized total revenue.",
  },
  {
    id: "panel-aggregate-revenue-entries",
    title: "Revenue Entries",
    renderer: "table",
    query: { dataSourceId: "revenue-aggregate", metric: "aggregate_revenue_entries", timeRange: "1m", refreshIntervalMs: 60000 },
    encoding: {},
    layout: { x: 0, y: 5, w: 12, h: 3 },
    description: "Latest income entries from all connected and manual revenue channels.",
  },
];

const zhupayPanels = [
  {
    id: "panel-zhupay-today-revenue",
    title: "Today Revenue",
    renderer: "kpi",
    query: { dataSourceId: "zhupay-payments", metric: "zhupay_today_revenue", timeRange: "1d", refreshIntervalMs: 60000 },
    encoding: { value: "value" },
    style: { colorIntent: "positive" },
    layout: { x: 0, y: 0, w: 3, h: 1 },
    description: "Revenue reported by Zhupay merchant info.",
  },
  {
    id: "panel-zhupay-balance",
    title: "Merchant Balance",
    renderer: "kpi",
    query: { dataSourceId: "zhupay-payments", metric: "zhupay_balance", timeRange: "1d", refreshIntervalMs: 60000 },
    encoding: { value: "value" },
    style: { colorIntent: "neutral" },
    layout: { x: 3, y: 0, w: 3, h: 1 },
    description: "Current merchant balance.",
  },
  {
    id: "panel-zhupay-today-orders",
    title: "Today Orders",
    renderer: "kpi",
    query: { dataSourceId: "zhupay-payments", metric: "zhupay_today_orders", timeRange: "1d", refreshIntervalMs: 60000 },
    encoding: { value: "value" },
    style: { colorIntent: "neutral" },
    layout: { x: 6, y: 0, w: 3, h: 1 },
    description: "Paid order count today.",
  },
  {
    id: "panel-zhupay-total-orders",
    title: "Total Orders",
    renderer: "kpi",
    query: { dataSourceId: "zhupay-payments", metric: "zhupay_total_orders", timeRange: "all", refreshIntervalMs: 60000 },
    encoding: { value: "value" },
    style: { colorIntent: "neutral" },
    layout: { x: 9, y: 0, w: 3, h: 1 },
    description: "Total order count from Zhupay.",
  },
  {
    id: "panel-zhupay-revenue-trend",
    title: "Revenue Trend",
    renderer: "lightweight-timeseries",
    query: { dataSourceId: "zhupay-payments", metric: "zhupay_revenue_trend", timeRange: "1d", refreshIntervalMs: 60000 },
    encoding: { x: "timestamp", y: "value" },
    style: { seriesStyle: "area", colorIntent: "primary" },
    interactions: { crosshair: true, zoom: true, rangeSwitcher: true },
    layout: { x: 0, y: 1, w: 12, h: 4 },
    description: "Paid order amount aggregated from locally synced Zhupay orders.",
  },
  {
    id: "panel-zhupay-recent-orders",
    title: "Recent Paid Orders",
    renderer: "table",
    query: { dataSourceId: "zhupay-payments", metric: "zhupay_recent_orders", timeRange: "1d", refreshIntervalMs: 60000 },
    encoding: {},
    layout: { x: 0, y: 5, w: 12, h: 3 },
    description: "Latest paid orders stored from Zhupay sync and notify callbacks.",
  },
];

const creemPanels = [
  {
    id: "panel-creem-today-revenue",
    title: "Today Revenue",
    renderer: "kpi",
    query: { dataSourceId: "creem-payments", metric: "creem_today_revenue", timeRange: "1d", refreshIntervalMs: 3600000 },
    encoding: { value: "value" },
    style: { colorIntent: "positive" },
    layout: { x: 0, y: 0, w: 3, h: 1 },
    description: "Net revenue from Creem transactions today.",
  },
  {
    id: "panel-creem-total-revenue",
    title: "Total Revenue",
    renderer: "kpi",
    query: { dataSourceId: "creem-payments", metric: "creem_total_revenue", timeRange: "all", refreshIntervalMs: 3600000 },
    encoding: { value: "value" },
    style: { colorIntent: "positive" },
    layout: { x: 3, y: 0, w: 3, h: 1 },
    description: "Total net Creem revenue cached locally.",
  },
  {
    id: "panel-creem-customers",
    title: "Customers",
    renderer: "kpi",
    query: { dataSourceId: "creem-payments", metric: "creem_customer_count", timeRange: "all", refreshIntervalMs: 3600000 },
    encoding: { value: "value" },
    style: { colorIntent: "neutral" },
    layout: { x: 6, y: 0, w: 3, h: 1 },
    description: "Customers synced from Creem.",
  },
  {
    id: "panel-creem-active-subscriptions",
    title: "Active Subscriptions",
    renderer: "kpi",
    query: { dataSourceId: "creem-payments", metric: "creem_active_subscriptions", timeRange: "all", refreshIntervalMs: 3600000 },
    encoding: { value: "value" },
    style: { colorIntent: "neutral" },
    layout: { x: 9, y: 0, w: 3, h: 1 },
    description: "Active and trialing subscriptions from Creem.",
  },
  {
    id: "panel-creem-revenue-trend",
    title: "Revenue Trend",
    renderer: "lightweight-timeseries",
    query: { dataSourceId: "creem-payments", metric: "creem_revenue_trend", timeRange: "1d", refreshIntervalMs: 3600000 },
    encoding: { x: "timestamp", y: "value" },
    style: { seriesStyle: "area", colorIntent: "primary" },
    interactions: { crosshair: true, zoom: true, rangeSwitcher: true },
    layout: { x: 0, y: 1, w: 12, h: 4 },
    description: "Net Creem transaction amount aggregated from local cache.",
  },
  {
    id: "panel-creem-recent-transactions",
    title: "Recent Transactions",
    renderer: "table",
    query: { dataSourceId: "creem-payments", metric: "creem_recent_transactions", timeRange: "1d", refreshIntervalMs: 3600000 },
    encoding: {},
    layout: { x: 0, y: 5, w: 12, h: 3 },
    description: "Latest Creem transactions from sync or verified webhooks.",
  },
];

const sub2apiPanels = [
  {
    id: "panel-sub2api-today-profit",
    title: "Today Earned",
    renderer: "kpi",
    query: { dataSourceId: "sub2api-usage", metric: "sub2api_today_profit", timeRange: "1d", refreshIntervalMs: 60000 },
    encoding: { value: "value" },
    style: { colorIntent: "positive" },
    layout: { x: 0, y: 0, w: 3, h: 1 },
    description: "Today earned revenue from Sub2API channel spend.",
  },
  {
    id: "panel-sub2api-total-profit",
    title: "Total Earned",
    renderer: "kpi",
    query: { dataSourceId: "sub2api-usage", metric: "sub2api_total_profit", timeRange: "all", refreshIntervalMs: 60000 },
    encoding: { value: "value" },
    style: { colorIntent: "positive" },
    layout: { x: 3, y: 0, w: 3, h: 1 },
    description: "Cumulative earned revenue from Sub2API channel spend.",
  },
  {
    id: "panel-sub2api-total-spend",
    title: "Total Spend",
    renderer: "kpi",
    query: { dataSourceId: "sub2api-usage", metric: "sub2api_total_spend", timeRange: "all", refreshIntervalMs: 60000 },
    encoding: { value: "value" },
    style: { colorIntent: "neutral" },
    layout: { x: 6, y: 0, w: 3, h: 1 },
    description: "Cumulative Sub2API actual cost before the profit-rate conversion.",
  },
  {
    id: "panel-sub2api-requests",
    title: "Requests",
    renderer: "kpi",
    query: { dataSourceId: "sub2api-usage", metric: "sub2api_request_count", timeRange: "all", refreshIntervalMs: 60000 },
    encoding: { value: "value" },
    style: { colorIntent: "neutral" },
    layout: { x: 9, y: 0, w: 3, h: 1 },
    description: "Total requests reported by configured Sub2API groups.",
  },
  {
    id: "panel-sub2api-profit-trend",
    title: "Daily Earned by Channel",
    renderer: "lightweight-timeseries",
    query: { dataSourceId: "sub2api-usage", metric: "sub2api_profit_trend", timeRange: "1m", refreshIntervalMs: 60000 },
    encoding: { x: "timestamp", y: "value", color: "series" },
    style: { seriesStyle: "line", colorIntent: "primary" },
    interactions: { crosshair: true, zoom: true, rangeSwitcher: true },
    layout: { x: 0, y: 1, w: 12, h: 4 },
    description: "Daily earned revenue from codex, codexplus, and total Sub2API usage.",
  },
  {
    id: "panel-sub2api-channel-breakdown",
    title: "Channel Breakdown",
    renderer: "table",
    query: { dataSourceId: "sub2api-usage", metric: "sub2api_channel_breakdown", timeRange: "all", refreshIntervalMs: 60000 },
    encoding: {},
    layout: { x: 0, y: 5, w: 12, h: 3 },
    description: "Configured Sub2API group cost, earned revenue, request count, and rate.",
  },
];

const dashboards = [
  {
    id: "dashboard-command-center",
    name: "Command Center",
    description: "Aggregated revenue cockpit across connected providers.",
    teamId: "team-core",
    defaultTimeRange: "1m",
    refreshIntervalMs: 60000,
    panels: aggregatePanels,
  },
  {
    id: "dashboard-zhupay-revenue",
    name: "Zhupay Revenue",
    description: "Zhupay merchant balance, order revenue, and paid order detail.",
    teamId: "team-core",
    defaultTimeRange: "1m",
    refreshIntervalMs: 60000,
    panels: zhupayPanels,
  },
  {
    id: "dashboard-creem-revenue",
    name: "Creem Revenue",
    description: "Creem transaction revenue, customers, subscriptions, and transaction detail.",
    teamId: "team-core",
    defaultTimeRange: "1m",
    refreshIntervalMs: 3600000,
    panels: creemPanels,
  },
  {
    id: "dashboard-sub2api-revenue",
    name: "Sub2API Earnings",
    description: "Sub2API codex and codexplus usage cost converted into earned revenue.",
    teamId: "team-core",
    defaultTimeRange: "1m",
    refreshIntervalMs: 60000,
    panels: sub2apiPanels,
  },
];

export const defaultAppState = {
  dataSources,
  metrics,
  activeDashboardId: "dashboard-command-center",
  dashboards,
  alerts: [],
  templates: [],
};
