export const defaultAppState = {
  dataSources: [
    {
      id: "zhupay-payments",
      name: "Zhupay Payments",
      kind: "zhupay",
      status: "draft",
      description: "Real Zhupay merchant balance, paid orders, and payment notifications.",
      endpoint: "https://pay.lxsd.cn",
      auth: "rsa",
      refreshIntervalMs: 60000,
      lastSyncAt: "",
      owner: "Revenue",
      fields: [
        { key: "captured_at", label: "Captured At", type: "time" },
        { key: "balance", label: "Merchant Balance", type: "number" },
        { key: "order_money_today", label: "Today Revenue", type: "number" },
        { key: "order_money_lastday", label: "Yesterday Revenue", type: "number" },
        { key: "order_num", label: "Total Orders", type: "number" },
        { key: "order_num_today", label: "Today Orders", type: "number" },
        { key: "trade_no", label: "Zhupay Trade No", type: "string" },
        { key: "out_trade_no", label: "Merchant Order No", type: "string" },
        { key: "type", label: "Payment Type", type: "string" },
        { key: "status", label: "Payment Status", type: "number" },
        { key: "name", label: "Product", type: "string" },
        { key: "money", label: "Order Amount", type: "number" },
        { key: "addtime", label: "Created At", type: "time" },
        { key: "endtime", label: "Paid At", type: "time" },
      ],
    },
    {
      id: "creem-payments",
      name: "Creem Payments",
      kind: "creem",
      status: "draft",
      description: "Real Creem transactions, customers, subscriptions, and webhook events.",
      endpoint: "https://api.creem.io",
      auth: "api-key",
      refreshIntervalMs: 3600000,
      lastSyncAt: "",
      owner: "Revenue",
      fields: [
        { key: "captured_at", label: "Captured At", type: "time" },
        { key: "total_revenue", label: "Total Revenue", type: "number" },
        { key: "today_revenue", label: "Today Revenue", type: "number" },
        { key: "transaction_count", label: "Transactions", type: "number" },
        { key: "customer_count", label: "Customers", type: "number" },
        { key: "active_subscription_count", label: "Active Subscriptions", type: "number" },
        { key: "id", label: "Transaction ID", type: "string" },
        { key: "type", label: "Transaction Type", type: "string" },
        { key: "status", label: "Transaction Status", type: "string" },
        { key: "amount_paid", label: "Amount Paid", type: "number" },
        { key: "refunded_amount", label: "Refunded Amount", type: "number" },
        { key: "currency", label: "Currency", type: "string" },
        { key: "customer_id", label: "Customer ID", type: "string" },
        { key: "subscription_id", label: "Subscription ID", type: "string" },
        { key: "source_created_at", label: "Created At", type: "time" },
      ],
    },
  ],
  metrics: [
    {
      id: "metric-zhupay-today-revenue",
      key: "zhupay_today_revenue",
      name: "Today Revenue",
      description: "Paid Zhupay order revenue reported by merchant info.",
      dataSourceId: "zhupay-payments",
      field: "order_money_today",
      timeField: "captured_at",
      aggregation: "latest",
      format: "currency",
      unit: "CNY",
      dimensions: [],
    },
    {
      id: "metric-zhupay-balance",
      key: "zhupay_balance",
      name: "Merchant Balance",
      description: "Current Zhupay merchant balance.",
      dataSourceId: "zhupay-payments",
      field: "balance",
      timeField: "captured_at",
      aggregation: "latest",
      format: "currency",
      unit: "CNY",
      dimensions: [],
    },
    {
      id: "metric-zhupay-today-orders",
      key: "zhupay_today_orders",
      name: "Today Orders",
      description: "Number of paid orders today.",
      dataSourceId: "zhupay-payments",
      field: "order_num_today",
      timeField: "captured_at",
      aggregation: "latest",
      format: "number",
      dimensions: [],
    },
    {
      id: "metric-zhupay-total-orders",
      key: "zhupay_total_orders",
      name: "Total Orders",
      description: "Total Zhupay order count reported by merchant info.",
      dataSourceId: "zhupay-payments",
      field: "order_num",
      timeField: "captured_at",
      aggregation: "latest",
      format: "number",
      dimensions: [],
    },
    {
      id: "metric-zhupay-revenue-trend",
      key: "zhupay_revenue_trend",
      name: "Revenue Trend",
      description: "Paid Zhupay order amount aggregated by time bucket.",
      dataSourceId: "zhupay-payments",
      field: "money",
      timeField: "endtime",
      aggregation: "sum",
      format: "currency",
      unit: "CNY",
      dimensions: ["type"],
    },
    {
      id: "metric-zhupay-recent-orders",
      key: "zhupay_recent_orders",
      name: "Recent Paid Orders",
      description: "Latest paid orders synced from Zhupay.",
      dataSourceId: "zhupay-payments",
      field: "money",
      timeField: "endtime",
      aggregation: "latest",
      format: "currency",
      unit: "CNY",
      dimensions: ["type", "status"],
    },
    {
      id: "metric-creem-today-revenue",
      key: "creem_today_revenue",
      name: "Creem Today Revenue",
      description: "Net paid Creem revenue for the current day in the configured reporting currency.",
      dataSourceId: "creem-payments",
      field: "today_revenue",
      timeField: "captured_at",
      aggregation: "latest",
      format: "currency",
      unit: "USD",
      dimensions: [],
    },
    {
      id: "metric-creem-total-revenue",
      key: "creem_total_revenue",
      name: "Creem Total Revenue",
      description: "Net paid Creem revenue synced into DataOcean.",
      dataSourceId: "creem-payments",
      field: "total_revenue",
      timeField: "captured_at",
      aggregation: "latest",
      format: "currency",
      unit: "USD",
      dimensions: [],
    },
    {
      id: "metric-creem-customer-count",
      key: "creem_customer_count",
      name: "Creem Customers",
      description: "Customers synced from Creem.",
      dataSourceId: "creem-payments",
      field: "customer_count",
      timeField: "captured_at",
      aggregation: "latest",
      format: "number",
      dimensions: [],
    },
    {
      id: "metric-creem-active-subscriptions",
      key: "creem_active_subscriptions",
      name: "Creem Active Subscriptions",
      description: "Active and trialing subscriptions synced from Creem.",
      dataSourceId: "creem-payments",
      field: "active_subscription_count",
      timeField: "captured_at",
      aggregation: "latest",
      format: "number",
      dimensions: [],
    },
    {
      id: "metric-creem-revenue-trend",
      key: "creem_revenue_trend",
      name: "Creem Revenue Trend",
      description: "Net Creem transaction revenue aggregated by time bucket.",
      dataSourceId: "creem-payments",
      field: "amount_paid",
      timeField: "source_created_at",
      aggregation: "sum",
      format: "currency",
      unit: "USD",
      dimensions: ["type", "status"],
    },
    {
      id: "metric-creem-recent-transactions",
      key: "creem_recent_transactions",
      name: "Creem Recent Transactions",
      description: "Latest transactions synced from Creem.",
      dataSourceId: "creem-payments",
      field: "amount_paid",
      timeField: "source_created_at",
      aggregation: "latest",
      format: "currency",
      unit: "USD",
      dimensions: ["type", "status", "currency"],
    },
  ],
  activeDashboardId: "dashboard-zhupay-revenue",
  dashboards: [
    {
      id: "dashboard-zhupay-revenue",
      name: "Revenue Command",
      description: "Real merchant revenue, balances, transactions, and subscription status from connected payment platforms.",
      teamId: "team-core",
      defaultTimeRange: "1d",
      refreshIntervalMs: 60000,
      panels: [
        {
          id: "panel-zhupay-today-revenue",
          title: "Today Revenue",
          renderer: "kpi",
          query: { dataSourceId: "zhupay-payments", metric: "zhupay_today_revenue", timeRange: "1d", refreshIntervalMs: 60000 },
          encoding: { value: "value" },
          style: { colorIntent: "positive" },
          layout: { x: 0, y: 0, w: 3, h: 1 },
          description: "Revenue reported by Zhupay merchant info.",
        },
        {
          id: "panel-zhupay-balance",
          title: "Merchant Balance",
          renderer: "kpi",
          query: { dataSourceId: "zhupay-payments", metric: "zhupay_balance", timeRange: "1d", refreshIntervalMs: 60000 },
          encoding: { value: "value" },
          style: { colorIntent: "neutral" },
          layout: { x: 3, y: 0, w: 3, h: 1 },
          description: "Current merchant balance.",
        },
        {
          id: "panel-zhupay-today-orders",
          title: "Today Orders",
          renderer: "kpi",
          query: { dataSourceId: "zhupay-payments", metric: "zhupay_today_orders", timeRange: "1d", refreshIntervalMs: 60000 },
          encoding: { value: "value" },
          style: { colorIntent: "neutral" },
          layout: { x: 6, y: 0, w: 3, h: 1 },
          description: "Paid order count today.",
        },
        {
          id: "panel-zhupay-total-orders",
          title: "Total Orders",
          renderer: "kpi",
          query: { dataSourceId: "zhupay-payments", metric: "zhupay_total_orders", timeRange: "all", refreshIntervalMs: 60000 },
          encoding: { value: "value" },
          style: { colorIntent: "neutral" },
          layout: { x: 9, y: 0, w: 3, h: 1 },
          description: "Total order count from Zhupay.",
        },
        {
          id: "panel-zhupay-revenue-trend",
          title: "Revenue Trend",
          renderer: "lightweight-timeseries",
          query: { dataSourceId: "zhupay-payments", metric: "zhupay_revenue_trend", timeRange: "1d", refreshIntervalMs: 60000 },
          encoding: { x: "timestamp", y: "value" },
          style: { seriesStyle: "area", colorIntent: "primary" },
          interactions: { crosshair: true, zoom: true, rangeSwitcher: true },
          layout: { x: 0, y: 1, w: 8, h: 4 },
          description: "Paid order amount aggregated from locally synced Zhupay orders.",
        },
        {
          id: "panel-zhupay-recent-orders",
          title: "Recent Paid Orders",
          renderer: "table",
          query: { dataSourceId: "zhupay-payments", metric: "zhupay_recent_orders", timeRange: "1d", refreshIntervalMs: 60000 },
          encoding: {},
          layout: { x: 0, y: 5, w: 12, h: 3 },
          description: "Latest paid orders stored from Zhupay sync and notify callbacks.",
        },
        {
          id: "panel-creem-today-revenue",
          title: "Creem Today Revenue",
          renderer: "kpi",
          query: { dataSourceId: "creem-payments", metric: "creem_today_revenue", timeRange: "1d", refreshIntervalMs: 3600000 },
          encoding: { value: "value" },
          style: { colorIntent: "positive" },
          layout: { x: 0, y: 8, w: 3, h: 1 },
          description: "Net revenue from Creem transactions today.",
        },
        {
          id: "panel-creem-total-revenue",
          title: "Creem Total Revenue",
          renderer: "kpi",
          query: { dataSourceId: "creem-payments", metric: "creem_total_revenue", timeRange: "all", refreshIntervalMs: 3600000 },
          encoding: { value: "value" },
          style: { colorIntent: "positive" },
          layout: { x: 3, y: 8, w: 3, h: 1 },
          description: "Total net Creem revenue cached locally.",
        },
        {
          id: "panel-creem-customers",
          title: "Creem Customers",
          renderer: "kpi",
          query: { dataSourceId: "creem-payments", metric: "creem_customer_count", timeRange: "all", refreshIntervalMs: 3600000 },
          encoding: { value: "value" },
          style: { colorIntent: "neutral" },
          layout: { x: 6, y: 8, w: 3, h: 1 },
          description: "Customers synced from Creem.",
        },
        {
          id: "panel-creem-active-subscriptions",
          title: "Creem Active Subscriptions",
          renderer: "kpi",
          query: { dataSourceId: "creem-payments", metric: "creem_active_subscriptions", timeRange: "all", refreshIntervalMs: 3600000 },
          encoding: { value: "value" },
          style: { colorIntent: "neutral" },
          layout: { x: 9, y: 8, w: 3, h: 1 },
          description: "Active and trialing subscriptions from Creem.",
        },
        {
          id: "panel-creem-revenue-trend",
          title: "Creem Revenue Trend",
          renderer: "lightweight-timeseries",
          query: { dataSourceId: "creem-payments", metric: "creem_revenue_trend", timeRange: "1d", refreshIntervalMs: 3600000 },
          encoding: { x: "timestamp", y: "value" },
          style: { seriesStyle: "area", colorIntent: "primary" },
          interactions: { crosshair: true, zoom: true, rangeSwitcher: true },
          layout: { x: 0, y: 9, w: 8, h: 4 },
          description: "Net Creem transaction amount aggregated from local cache.",
        },
        {
          id: "panel-creem-recent-transactions",
          title: "Creem Recent Transactions",
          renderer: "table",
          query: { dataSourceId: "creem-payments", metric: "creem_recent_transactions", timeRange: "1d", refreshIntervalMs: 3600000 },
          encoding: {},
          layout: { x: 0, y: 13, w: 12, h: 3 },
          description: "Latest Creem transactions from sync or verified webhooks.",
        },
      ],
    },
  ],
  alerts: [],
  templates: [],
};
